### ISSUE TITLE
Server still running after stopping Nodemon

### ISSUE THREAD

**Issue by Bhargav252000** [remy/nodemon#1867]
- `nodemon -v`:  2.0.7
- `node -v`: 14.17.0
- Operating system/terminal environment:  WSL2 Ubuntu 20.04

### Expected behaviour

The server stops after using `ctrl + c`, and not run in background

### Actual behaviour
The server doesn't stops after `ctrl + c` and it keeps runs in background even after uninstalling

### Steps to reproduce
I started the server using nodemon and my script was `"server": "npx nodemon app.js"` and ran `npm server start`
But server is still running in the Browser, I can't start any other server on that same port i.e `3000`
app.js is a simple express app

**Comment by remy** [comment]
Please re-test with nodemon@2.0.9 - windows specific fixes have been added.

**Comment by GalaxySH** [comment]
> 
> 
> Please re-test with nodemon@2.0.9 - windows specific fixes have been added.

I installed nodemon@2.0.9 (global) and am still having the persistent server issue. I'm not getting the local windows-kill binary not found error anymore, however.

**Comment by remy** [comment]
You're going to have to add some actual detail on what you're testing and what you're seeing then.

**Comment by GalaxySH** [comment]
I don't know what else to tell you that could be useful. You mentioned a fix in the latest version, and it obviously didn't work.

I am running this on node 14.11 with nodemon launching from a startup script (`nodemon --exec npm run start`). When the nodemon restart event is triggered, it seemingly restarts the application (script is executed again, files are reloaded), but when the script gets to the server creation step, it encounters the `EADDRINUSE` error for the port the server is always started on and the application shard just keeps restarting and getting the same error.

When I forcefully exit the application (^C) and restart from the same nodemon script, the port is seemingly opened up and it can start again, until nodemon tries to restart. What I deduce from this is that when nodemon restarts the app, some part of it is left running (I am not privy to the deeper workings of node or nodemon so I cannot elaborate) and the port remains in use. When I ^C, the app is actually stopped.

**Comment by remy** [comment]
Screenshot and a parred down version of your app.js to test with.

**Comment by mlarabi** [comment]
Yesterday I decided to upgrade my packages to the last version of each one. And since then this issue appeared. I am not able to debug correctly as my server keep running when restarted.
Before the upgrade, every thing was working fine. I tried to downgrade just `nodemon` or `npm-watch` (I am using `nodemon` through `npm-watch`) and it didn't solve the issue, so I am guessing that it is something else that got upgrade and keep blocking `nodemon` for shutting down the server.

Here is my current `package.json` if it can help to solve the issue.

```{
  "dependencies": {
    "@sentry/node": "^6.8.0",
    "@sentry/tracing": "^6.8.0",
    "dotenv": "^10.0.0",
    "ejs": "^3.1.6",
    "express": "^4.17.1",
    "morgan": "^1.10.0",
    "pg": "^8.6.0",
    "sequelize": "^6.6.4",
    "winston": "^3.3.3"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.14.5",
    "@babel/preset-typescript": "^7.13.0",
    "@types/ejs": "^3.0.6",
    "@types/express": "^4.17.12",
    "@types/jest": "^26.0.23",
    "@types/morgan": "^1.9.2",
    "@types/node": "^16.0.0",
    "@types/sequelize": "^4.28.9",
    "@types/serve-static": "^1.13.9",
    "@types/validator": "^13.6.0",
    "babel-jest": "^27.0.2",
    "del-cli": "^4.0.0",
    "jest": "^27.0.4",
    "kill-port": "^1.6.1",
    "nodemon": "^2.0.9",
    "npm-watch": "^0.10.0",
    "raw-loader": "^4.0.2",
    "sass": "^1.34.0",
    "sass-loader": "^12.1.0",
    "sequelize-cli": "^6.2.0",
    "ts-loader": "^9.2.2",
    "tsconfig-paths-webpack-plugin": "^3.5.1",
    "typescript": "^4.3.2",
    "webpack-cli": "^4.7.0",
    "webpack-node-externals": "^3.0.0"
  }
```

As for me, I followed [this answer on Stackoverflow](https://stackoverflow.com/questions/58605392/port-3000-is-already-in-use-nodemon-app-crashed-waiting-for-file-changes-bef) and it helped me resolve this issue but it would be nice if I don't have to go through other packages to get this working.

**Comment by remy** [comment]
Should be fixed in nodemon@2.0.9 and above.

**Comment by GalaxySH** [comment]
Well, it's not

**Comment by remy** [comment]
> Well, it's not

https://github.com/remy/nodemon/issues/1867#issuecomment-873537674

**Comment by mlarabi** [comment]
Same here, the issue is still there.
I created a project that could help reproduce the error on your side: https://github.com/mlarabi/nodemon-restart-issue
To reproduce the error, you need to clone the project, install the node modules, and run `npm run watch`. After this, you'll just have to modify the `index.js` file during the watch to see the error happening.

https://user-images.githubusercontent.com/75162562/125224709-60cb2b00-e2ce-11eb-8f36-62673f01b354.mp4

**Comment by mlarabi** [comment]
After further tests using the repo above it seems that nodemon works just fine.
Using `nodemon index.js` the server does restart as expected. So the issue is more on `npm-watch`, for me at least.

https://user-images.githubusercontent.com/75162562/125225811-2b274180-e2d0-11eb-9987-bc6c23e9cda8.mp4
