### ISSUE TITLE
Nodemon not restarting: [nodemon] restarting due to changes.

### ISSUE THREAD

**Issue by moksedulislam** [remy/nodemon#1882]
Nodemon not restarting: [nodemon] restarting due to changes... i use vs code if change my code but not update my code browser and show restarting use due to change 

- `nodemon -v`:2.0.9
- `node -v`:v16.0.0
- Operating system/terminal environment: windows 10 vs code terminal
- Using Docker? What image: 
- Command you ran: nodemon index.js

### Expected behaviour
`const http = require("http");
const PORT = 3000;
const hostName = "127.0.0.1";
const server = http.createServer((req,res) => {
    res.end("Welco my server  server test test");
})
server.listen(PORT,hostName, () => {
    console.log(`server is running at http://${hostName}:${PORT}`)
})`

### Steps to reproduce
[nodemon] 2.0.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
server is running at http://127.0.0.1:3000
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by Pitonuss** [comment]
Same problem.

> nodemon -v:2.0.8/2.0.9/2.0.10
> node -v:v14.17.3
> Operating system/terminal environment: windows 10 vs code terminal

The latest version where it works correctly is 2.0.7

**Comment by milanmdev** [comment]
On v2.0.11 or v2.0.10 is where it's broken iirc

**Comment by remy** [comment]
Can you all (3 ppl) provide screenshots of the screens showing what you're seeing

**Comment by moksedulislam** [comment]
> Can you all (3 ppl) provide screenshots of the screens showing what you're seeing

![Screenshot_20](https://user-images.githubusercontent.com/87057441/125156310-a5e44580-e186-11eb-94ea-dd61dc03a7c9.png)

**Comment by milanmdev** [comment]
> Can you all (3 ppl) provide screenshots of the screens showing what you're seeing

Currently not at my Windows pc. The error occurs over there, but not on my Mac.

**Comment by mikenavi** [comment]
same issue

**Comment by remy** [comment]
Those of you on node 15 and 16, can you test with node 14 (or 12) just to rule node versions out of the equation?

**Comment by mikenavi** [comment]
> Those of you on node 15 and 16, can you test with node 14 (or 12) just to rule node versions out of the equation?

![Image 25](https://user-images.githubusercontent.com/4928270/125177203-7fec8e80-e1e2-11eb-86d4-5f1f08bd2738.png)

**Comment by vayupuk** [comment]
I have same problem.
node v 14.17.3
nodemon v 2.0.12

And I fixed that by installed **nodemon @2.0.7** 

then It work.

**Comment by Sergey-Zhestovsky** [comment]
Have kind of the same problem.
node v 16.4.0
nodemon v ^2.0.8

Fixed by installing nodemon@2.0.7.

Although for me, server is restarting, but several times for no reason.
![Screenshot 2021-07-23 125641](https://user-images.githubusercontent.com/18037331/126767665-5213b005-1c12-4d28-9724-7d61603a7db5.png)

**Comment by remy** [comment]
Just to rule it out - can we try with `nodemon@2.0.13-alpha.1` aka `npm install -g nodemon@debug` and report back? Thank you.

**Comment by mikenavi** [comment]
> Just to rule it out - can we try with `nodemon@2.0.13-alpha.1` aka `npm install -g nodemon@debug` and report back? Thank you.

no changes in my case

![image](https://user-images.githubusercontent.com/4928270/127139884-0d6c9a51-8b31-424f-99e2-898013185014.png)

**Comment by Icaruk** [comment]
`npm i nodemon@2.0.7`

Fixed the issue for me.

**Comment by Bikramghimire** [comment]
![Screenshot (131)](https://user-images.githubusercontent.com/43429038/128125088-1ad075a6-44a2-4f25-8a1f-f5d8d0846dc7.png)
how you guys solve this problem anyone?? tired everything install nodemon globally degraded the version to 2.0.7, even uninstall nodejs and install new node and added all path in environment variables .......

**Comment by Icaruk** [comment]
> ![Screenshot (131)](https://user-images.githubusercontent.com/43429038/128125088-1ad075a6-44a2-4f25-8a1f-f5d8d0846dc7.png)
> how you guys solve this problem anyone?? tired everything install nodemon globally degraded the version to 2.0.7, even uninstall nodejs and install new node and added all path in environment variables .......

Try to `npm un nodemon` on your project.
Then `npm i -g nodemon@2.0.7`.

Terminate process and try again.

**Comment by lukasbryla** [comment]
I had the same problem. Downgrading -g nodemon to 2.0.7 fixed it.

**Comment by yulaie1012** [comment]
I have the same problem.
node -v 14.16.0
nodemon -v 2.0.7

<img width="683" alt="Screenshot_1" src="https://user-images.githubusercontent.com/25324243/132228703-8a60f6a5-184c-40fb-9eee-ada460bac395.png">

**Comment by Icaruk** [comment]
> I have the same problem.
> node -v 14.16.0
> nodemon -v 2.0.7
> 
> <img width="683" alt="Screenshot_1" src="https://user-images.githubusercontent.com/25324243/132228703-8a60f6a5-184c-40fb-9eee-ada460bac395.png">
> 

Check if you have installed nodemon globally

**Comment by Bikramghimire** [comment]
> I have the same problem.
> node -v 14.16.0
> nodemon -v 2.0.7
> 
> <img alt="Screenshot_1" width="683" src="https://user-images.githubusercontent.com/25324243/132228703-8a60f6a5-184c-40fb-9eee-ada460bac395.png">

i have also the same problem. i tried every thing find on internet but does not work then i used alternative of nodemon . recently , i have reset my operating system then i install nodemon then it works so OS was causing the problem.

**Comment by yulaie1012** [comment]
> > I have the same problem.
> > node -v 14.16.0
> > nodemon -v 2.0.7
> > <img alt="Screenshot_1" width="683" src="https://user-images.githubusercontent.com/25324243/132228703-8a60f6a5-184c-40fb-9eee-ada460bac395.png">
> 
> Check if you have installed nodemon globally

Yes, nodemon is installed globally.

**Comment by niquedegraaff** [comment]
I can verify that it is broken above 2.0.7

**Comment by curtiskeisler** [comment]
> I have same problem.
> node v 14.17.3
> nodemon v 2.0.12
> 
> And I fixed that by installed **nodemon @2.0.7**
> 
> then It work.

I had the same problem, 
nodemon 2.0.12
Windows 10
VS Code 1.60.0
Node.js 14.16.0

down graded to nodemon 2.0.7 and it works beautifully again when I save . . . 

restarts and works as  expected

upgrade back to @latest nodemon . . . restart never occurs . . there's a message saying that it's restarting due to changes . . . it just never does.

**Comment by Icaruk** [comment]
> > > I have the same problem.
> > > node -v 14.16.0
> > > nodemon -v 2.0.7
> > > <img alt="Screenshot_1" width="683" src="https://user-images.githubusercontent.com/25324243/132228703-8a60f6a5-184c-40fb-9eee-ada460bac395.png">
> > 
> > 
> > Check if you have installed nodemon globally
> 
> Yes, nodemon is installed globally.

Uninstall locally and globally, then install the version 2.0.7

**Comment by fabriciorsf** [comment]
The same problem with me at Windows 10:
`nodemon -v 2.0.12`
`node -v 14.17.6`

**Comment by sb-baris** [comment]
Same problem here on Windows 10 + VSCode. 

`[nodemon] restarting due to changnges...` but never restarts.

`nodemon -v 2.0.12`
`node -v 12.22.4`

Reverting to version nodemon v2.0.7 works around the problem for me, too. But still, an actual fix would solve my problem in our team, since I cannot commit version downgrade to our codebase.

**Comment by Xairoo** [comment]
2.0.7 works.

Maybe some others run into this too:

It looks like 2.0.12 sometimes ignores some code changes. But I am not 100% sure it because of nodemon, guess nodemon doesn't use caching or so? But my SSD works fine.
Results in processing old code, the code before saving. This won't happen anymore since the downgrade to 2.0.7. Haven't restarted my Windows Terminal, neither have rebooted my system. It's a bit gross.

**Comment by remy** [comment]
If anyone is still watching this issue - let's try to hit reset.

The first thing I need is for anyone that can replicate this, or is still experiencing this issue to pipe up.

Then, if it still affects you, I need the following (sorry to be harsh, but all other "also affects me" will be either ignored or deleted - need to focus on where the issue is):

- `node -e 'console.log(`node@${process.version}, ${process.platform}@${require(\"os\").release()}`)'`
- `node -v`
- `nodemon -v`
- **MOST IMPORTANTLY** what shell are you running: PowerShell, git bash, etc.
- Are you running inside of VS Code?

If you're using VS Code, I'm going to request that you replicate _outside_ of VS Code as I'm starting to wonder if there might be something going on here because as yet I can't replicate (and I tend to cut VS Code out of the replication process since I can never be sure exactly which shell it's running).

**Comment by Xairoo** [comment]
- PowerShell v5.1.19041.1237 (`Get-Host | Select-Object Version`), running in Windows Terminal
- node v14.15.4
- nodemon v2.0.12

Can also be reproduced with git-bash and git-cmd.

**Comment by sb-baris** [comment]
The command `node -e 'console.log(node@${process.version}, ${process.platform}@${require("os").release()})'` didn't work on my PC, but here are its components:

- process.version = 'v12.22.4'
- process.platform = 'win32'
- require("os").release() = '10.0.19043'
- node v12.22.4
- nodemon v2.0.12

And the important point on my side is, the problem only happens if I run it in VSCode integrated terminal (PowerShell) and in **DEBUG** mode. When not in debug mode, with the PowerShell in VSCode, nodemon restarts just fine, also outside VSCode.

I don't know how to run debug mode outside VSCode. So I could not check that. Also, I don't know how to change with terminal VSCode uses for debug mode.

But I tried it with WebStorm, too. There I can set which terminal is used for debug mode. And, in Debug mode, PowerShell terminal made the same problem, whereas other terminals (cmd, wsl) worked just fine in debug mode.

So on my side, the problem looks somehow related to debug+powershell, instead of VSCode directly.

**Comment by remy** [comment]
@sb-baris useful - thank you.

@Xairoo are you running inside of vscode? are you running in debug mode (as @sb-baris comments)?

**Comment by Xairoo** [comment]
> @Xairoo are you running inside of vscode? are you running in debug mode (as @sb-baris comments)?

> 
>     * PowerShell v5.1.19041.1237 (`Get-Host | Select-Object Version`), running in Windows Terminal
> 

directly in Windows Terminal and not in VS Code, also no debug mode. No idea if you use Windows. https://github.com/microsoft/terminal

nodemon in wsl doesn't trigger a restart.

**Comment by bartick** [comment]
I have a different results than with running nodemon.
(I might be doing something wrong as today is the first day I am using nodemon)
```
process.version = 'v16.8.0'
process.platform = 'win32'
require("os").release() = '10.0.19043'
node v16.8.0
nodemon v2.0.12
```
On Using VS code It shows restarting on file edit but never restarts (cmd and powershell) .
Outside vs code (In cmd or powershell [both have same issue]) On file edits it never restarts nor even shows restart. On pressing `ctrl+c` it shows the restarting message but still never restarts.    (I never used debug mode on the whole process)

I tried installing nodemon v2.0.7 and it works find inside and outside vs code

**Comment by AbhishekNarula28** [comment]
@remy I tried everything that was mentioned in this issue and I'm still getting the restarting due to changes error. I even tried the debug build aka `npm i -g nodemon@debug` but it didn't resolve the issue. Also `node -e 'console.log(node@${process.version}, ${process.platform}@${require("os").release()})'` command didn't work for me.
I am using:
Node v14.17.6
Nodemon v2.0.13-alpha.1
![Restart](https://user-images.githubusercontent.com/65360436/134870362-8c069d68-bb6a-4e89-b700-c93cadbfb4c0.png)


 Hoping to hear from you.

**Comment by remy** [comment]
@AbhishekNarula28 what terminal shell are you using?

**Comment by remy** [comment]
Version? You need to be specific since I can't replicate.

**Comment by AbhishekNarula28** [comment]
5.1.19041.1237

**Comment by SagiDeveloper** [comment]
> I had the same problem. Downgrading -g nodemon to 2.0.7 fixed it.
Worked for me (Node v14.17.6)

**Comment by AbhishekNarula28** [comment]
> 
> 
> > I had the same problem. Downgrading -g nodemon to 2.0.7 fixed it.
> 
> Worked for me (Node v14.17.6)
> 
> npm un nodemon npm i -g nodemon@2.0.7
> 
> Terminate process and try again.

I fixed it on 2.0.13.

**Comment by jordanlun1** [comment]
> > > I had the same problem. Downgrading -g nodemon to 2.0.7 fixed it.
> > 
> > 
> > Worked for me (Node v14.17.6)
> > npm un nodemon npm i -g nodemon@2.0.7
> > Terminate process and try again.
> 
> I fixed it on 2.0.13.

I just tried 2.0.13 and it's still doing it. Fine with 2.0.7

**Comment by immortalmind2016** [comment]
Can people following this thread test with `npm i nodemon@debug` and confirm if this works or not

**Comment by immortalmind2016** [comment]
@sb-baris  thanks for the test 
@remy  it is working with @sb-baris

**Comment by JoeyFlaum** [comment]
Still not restarting for me. 

Windows 10.0.19042
Node  16.13.0
Nodemon 2.0.14-alpha.1

I tried going back to 2.0.7  and 1.19.4

Error: listen EADDRINUSE: address already in use 

I tried killing all ports in use and the problem just starts again when starting the nodemon script.

**Comment by immortalmind2016** [comment]
use the last version `npm install nodemon`
and check if your package.json includes nodemon you may use it inside instead of global one

**Comment by JoeyFlaum** [comment]
I started with 2.0.14(latest version) which is what was not working in the first place. My last try was the 2.0.14-alpha.1 version. Nothing is working🤷‍♂️

**Comment by varun015** [comment]
Not working for me.
